### ISSUE TITLE
asset of resource type BillingAccount or Organization do not need to have a parent

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/terraform-validator#106] opened 2019-11-20 05:41 UTC
https://github.com/GoogleCloudPlatform/terraform-validator/blob/3cdd6e984bb99bf6db7e87d58222ffe96379fe74/converters/google/convert.go#L210-L216

Removing parent for these types should make the result more aligning with CAI.

**Comment by yukinying** [comment] 2019-11-20 07:48
This is probably not a bug but a feature to be added. Neither resource type `BillingAccount` nor `Organization` is converted by the supported terraform configuration yet.

**Comment by morgante** [comment] 2019-11-20 09:10
We'll also have to assess the right parent for folders.

**Comment by yukinying** [comment] 2019-11-20 23:21
I was looking at how we can find parents for folder. It looks like getAncestry API in resource manager only support looking up ancestors for project. So we can use ancestry cache if folder is within the path of the project, or we will not be able to find the ancestry for folder. I am worried about the later. What's your thought on that, e.g. what is the proper value to fill there? Nil? Placeholder? 

Also, I was looking at the code in forseti-security/config-validator and it looks like the field is not used.

**Comment by morgante** [comment] 2019-11-21 23:18
> So we can use ancestry cache if folder is within the path of the project, or we will not be able to find the ancestry for folder. I am worried about the later.

I'm thinking we could leverage the ancestry cache in combination with any other folder resources defined in a config. Not a high priority though.

> What's your thought on that, e.g. what is the proper value to fill there? Nil? Placeholder?
Probably just the folder itself if we don't have additional info.

**Comment by melinath** [comment] 2021-05-03 21:21
I think this is a duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/206 but please re-open & clarify if not!

**Closed by melinath** 2021-05-03 21:21 UTC
