### ISSUE TITLE
Fix asset.resource.parent for top-level resources

### ISSUE THREAD

**Issue by nstogner** [GoogleCloudPlatform/terraform-validator#5] opened 2019-04-01 19:28 UTC
Currently `asset.resource.parent` assumes the resource lives within a project. This does not work for folders, etc.

**Comment by nstogner** [comment] 2019-04-04 00:55
Strategy: Move the calculation parent upstream into the conversions library. See GoogleCloudPlatform/magic-modules#1620.

**Comment by melinath** [comment] 2021-05-03 21:54
Closing due to lack of detail. If you'd like to add some detail, please open a new issue! This may also be a duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/206

**Closed by melinath** 2021-05-03 21:54 UTC
