### ISSUE TITLE
Fails to convert `google_folder_iam`

### ISSUE THREAD

**Issue by ews99** [GoogleCloudPlatform/terraform-validator#150] opened 2020-08-26 13:00 UTC
```
Error: converting tfplan to CAI assets: converting resource google_folder_iam_member: augmenting asset: project: required field is not set
```

Field `project` is not required for this resource, see: https://www.terraform.io/docs/providers/google/r/google_folder_iam.html#google_folder_iam_member

This issue is very similar to #42 and should be fixed, but it isn't in my used version (installed terraform-validator from the gs bucket, gs://terraform-validator/releases/2020-03-05/terraform-validator-linux-amd64)

**Comment by melinath** [comment] 2021-03-24 18:58
Closing as a duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/206 - if you believe this is in error, please reopen. Otherwise, please upvote the other issue. Thanks!

**Closed by melinath** 2021-03-24 18:58 UTC
Labels: bug
