### ISSUE TITLE
Fails to convert `google_organization_iam_member`

### ISSUE THREAD

**Issue by ocervell** [GoogleCloudPlatform/terraform-validator#42] opened 2019-06-12 14:29 UTC
```
Error: converting tfplan to CAI assets: converting resource google_organization_iam_member: augmenting asset: project: required field is not set
```

Field `project` is not required for this resource (cf. https://www.terraform.io/docs/providers/google/r/google_organization_iam_member.html)

**Comment by yukinying** [comment] 2019-11-20 05:55
It looks like a fix on https://github.com/GoogleCloudPlatform/terraform-validator/issues/105 would remove the need of having the checks on `project: required field is not set`.

**Comment by agosto-lorinronken** [comment] 2019-12-03 21:48
I am receiving this same issue when attempting to create the resource 'google_project'.  

`Error: converting tfplan to CAI assets: converting resource google_project: augmenting asset: project: required field is not set
`

However, the `project` field is not required by this resource: https://www.terraform.io/docs/providers/google/r/google_project.html

**Comment by melinath** [comment] 2021-03-24 18:58
Closing as a duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/206 - if you believe this is in error, please reopen. Otherwise, please upvote the other issue. Thanks!

**Closed by melinath** 2021-03-24 18:58 UTC
Labels: bug
