### ISSUE TITLE
Error using Terraform plan (Terraform 0.12.20)

### ISSUE THREAD

**Issue by nlamirault** [GoogleCloudPlatform/terraform-validator#138] opened 2020-05-07 06:55 UTC
I make a change on disk size to try terraform-validator.

```Makefile
.PHONY: terraform-policy
terraform-policy:
	@echo -e "$(OK_COLOR)[$(APP)] Check infrastructure$(NO_COLOR)"
	@cd $(SERVICE)/terraform \
		&& terraform init -lock-timeout=60s -reconfigure -backend-config=backend-vars/$(ENV).tfvars \
		&& terraform plan -lock-timeout=60s -var-file=tfvars/$(ENV).tfvars --out=terraform.tfplan \
		&& terraform show -json ./terraform.tfplan > ./terraform.tfplan.json \
		&& terraform-validator validate --policy-path=$(TF_POLICY_PATH) ./terraform.tfplan.json
```

```
~ resource "google_compute_region_disk" "ftp" {
        creation_timestamp        = "2020-05-06T09:09:31.106-07:00"
        description               = "Created by Terraform"
        id                        = "projects/xxxxx/regions/europe-west1/disks/preprod-disk"
        last_attach_timestamp     = "2020-05-06T09:23:42.089-07:00"
        name                      = "preprod-disk"
        physical_block_size_bytes = 4096
        project                   = "xxxxxxxxx"
        region                    = "europe-west1"
        replica_zones             = [
            "https://www.googleapis.com/compute/v1/projects/xxxxxxx/zones/europe-west1-b",
            "https://www.googleapis.com/compute/v1/projects/xxxxxxx/zones/europe-west1-d",
        ]
        self_link                 = "https://www.googleapis.com/compute/v1/projects/xxxxxxx/regions/europe-west1/disks/preprod-disk"
      ~ size                      = 200 -> 2000
        type                      = "pd-standard"
        users                     = [
            "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxx/zones/europe-west1-b/instances/preprod-ftp-server1",
        ]
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: terraform.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "terraform.tfplan"

Error: converting tfplan to CAI assets: reading terraform plan: not a valid plan file
Usage:
  terraform-validator validate <tfplan> [flags]

Flags:
  -h, --help                 help for validate
      --output-json          Print violations as JSON
      --policy-path string   Path to directory containing validation policies
      --project string       Provider project override (override the default project configuration assigned to the google terraform provider when validating resources)

Global Flags:
      --verbose   Log output to stderr
```
json plan seems good.

No error with TF : 

```
$ terraform show -json terraform.tfplan                                                                {"format_version":"0.1","terraform_version":"0.12.20","variables":{ ....
```

Any idea ?

**Comment by morgante** [comment] 2020-05-07 14:18
Does this still occur if you run validator directly (outside of your Make script)?

**Comment by nlamirault** [comment] 2020-06-12 16:27
@morgante yes.

**Comment by morgante** [comment] 2020-06-12 16:29
Hmm, I'm having trouble reproducing. Can you paste your plan JSON?

**Comment by nlamirault** [comment] 2020-06-12 16:33
```json
{"format_version":"0.1","terraform_version":"0.12.20","variables":{"bucket_name":{"value":"foobar-prod-terraform-tfstates"},"project":{"value":"foobar"},"region":{"value":"europe-west1"}},"planned_values":{"root_module":{"resources":[{"address":"google_storage_bucket.terraform_tfstate","mode":"managed","type":"google_storage_bucket","name":"terraform_tfstate","provider_name":"google","schema_version":0,"values":{"bucket_policy_only":false,"cors":[],"default_event_based_hold":false,"encryption":[],"force_destroy":false,"id":"foobar-prod-terraform-tfstates","labels":{},"lifecycle_rule":[],"location":"EU","logging":[],"name":"foobar-prod-terraform-tfstates","project":"foobar","requester_pays":false,"retention_policy":[],"self_link":"https://www.googleapis.com/storage/v1/b/foobar-prod-terraform-tfstates","storage_class":"MULTI_REGIONAL","url":"gs://foobar-prod-terraform-tfstates","versioning":[{"enabled":true}],"website":[]}}]}},"resource_changes":[{"address":"google_storage_bucket.terraform_tfstate","mode":"managed","type":"google_storage_bucket","name":"terraform_tfstate","provider_name":"google","change":{"actions":["no-op"],"before":{"bucket_policy_only":false,"cors":[],"default_event_based_hold":false,"encryption":[],"force_destroy":false,"id":"foobar-prod-terraform-tfstates","labels":{},"lifecycle_rule":[],"location":"EU","logging":[],"name":"foobar-prod-terraform-tfstates","project":"foobar","requester_pays":false,"retention_policy":[],"self_link":"https://www.googleapis.com/storage/v1/b/foobar-prod-terraform-tfstates","storage_class":"MULTI_REGIONAL","url":"gs://foobar-prod-terraform-tfstates","versioning":[{"enabled":true}],"website":[]},"after":{"bucket_policy_only":false,"cors":[],"default_event_based_hold":false,"encryption":[],"force_destroy":false,"id":"foobar-prod-terraform-tfstates","labels":{},"lifecycle_rule":[],"location":"EU","logging":[],"name":"foobar-prod-terraform-tfstates","project":"foobar","requester_pays":false,"retention_policy":[],"self_link":"https://www.googleapis.com/storage/v1/b/foobar-prod-terraform-tfstates","storage_class":"MULTI_REGIONAL","url":"gs://foobar-prod-terraform-tfstates","versioning":[{"enabled":true}],"website":[]},"after_unknown":{}}}],"prior_state":{"format_version":"0.1","terraform_version":"0.12.20","values":{"root_module":{"resources":[{"address":"google_storage_bucket.terraform_tfstate","mode":"managed","type":"google_storage_bucket","name":"terraform_tfstate","provider_name":"google","schema_version":0,"values":{"bucket_policy_only":false,"cors":[],"default_event_based_hold":false,"encryption":[],"force_destroy":false,"id":"foobar-prod-terraform-tfstates","labels":{},"lifecycle_rule":[],"location":"EU","logging":[],"name":"foobar-prod-terraform-tfstates","project":"foobar","requester_pays":false,"retention_policy":[],"self_link":"https://www.googleapis.com/storage/v1/b/foobar-prod-terraform-tfstates","storage_class":"MULTI_REGIONAL","url":"gs://foobar-prod-terraform-tfstates","versioning":[{"enabled":true}],"website":[]}}]}}},"configuration":{"provider_config":{"google":{"name":"google","expressions":{"project":{"references":["var.project"]},"region":{"references":["var.region"]}}}},"root_module":{"resources":[{"address":"google_storage_bucket.terraform_tfstate","mode":"managed","type":"google_storage_bucket","name":"terraform_tfstate","provider_config_key":"google","expressions":{"location":{"constant_value":"eu"},"name":{"references":["var.bucket_name"]},"storage_class":{"constant_value":"MULTI_REGIONAL"},"versioning":[{"enabled":{"constant_value":true}}]},"schema_version":0}],"variables":{"bucket_name":{},"project":{},"region":{}}}}}
```

**Comment by melinath** [comment] 2021-03-23 21:35
@nlamirault Are you still experiencing this issue / have you found anything else out about it?

**Comment by melinath** [comment] 2021-12-20 21:28
From the description, it sounds like maybe terraform-validator was being used directly on a binary plan file, which is not supported. I can't reproduce using the provided plan json. Closing for now - please open a new issue with more details if you're still experiencing this issue! Thanks!

**Closed by melinath** 2021-12-20 21:28 UTC
Labels: bug
