### ISSUE TITLE
Nonfatal "ERROR: logging before flag.Parse"

### ISSUE THREAD

**Issue by jdav-goog** [GoogleCloudPlatform/terraform-validator#144] opened 2020-06-19 13:43 UTC
The validator works fine but we are getting these nonfatal error. Is this something on our end?

![Screen Shot 2020-06-18 at 4 08 32 PM](https://user-images.githubusercontent.com/61511931/85138607-ac64ef80-b208-11ea-9e9f-2384fd1f5433.png)

**Comment by morgante** [comment] 2020-06-19 18:02
It's a bug in our logging tool, but you can safely ignore it.

**Comment by melinath** [comment] 2021-05-03 18:11
closing - duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/122

**Closed by melinath** 2021-05-03 18:11 UTC
