### ISSUE TITLE
FCV: initializing gcv validator: failed to read files in /workspace/policy-library/policies

### ISSUE THREAD

**Issue by jasonbisson** [GoogleCloudPlatform/terraform-validator#188] opened 2021-02-24 01:55 UTC
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": ------------------------------------------------------------------------
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This plan was saved to: /workspace/tmp_plan/envs-shared.tfplan
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": To perform exactly these actions, run the following command to apply:
Step #1 - "tf plan validate all":     terraform apply "/workspace/tmp_plan/envs-shared.tfplan"
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": *************** TERRAFORM VALIDATE ******************
Step #1 - "tf plan validate all":       At environment: envs/shared 
Step #1 - "tf plan validate all":       Using policy from: /workspace/policy-library 
Step #1 - "tf plan validate all": *****************************************************
Step #1 - "tf plan validate all": WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@prj-seed-.iam.gserviceaccount.com].
Step #1 - "tf plan validate all": WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@prj-seed-.iam.gserviceaccount.com].
Step #1 - "tf plan validate all": WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@prj-seed-.iam.gserviceaccount.com].
Step #1 - "tf plan validate all": Cloning into '/workspace/policy-library'...
Step #1 - "tf plan validate all": WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@prj-seed-.iam.gserviceaccount.com].
Step #1 - "tf plan validate all": warning: You appear to have cloned an empty repository.
Step #1 - "tf plan validate all": Project [prj-cloudbuild-] repository [gcp-policies] was cloned to [/workspace/policy-library].
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: W0224 01:10:40.899692     493 planned_assets.go:57] converting resource: asset type cloudbilling.googleapis.com/ProjectBillingInfo: asset name //cloudbilling.googleapis.com/projects/prj-cloudbuild-/billingInfo: duplicate asset
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: W0224 01:10:40.899768     493 planned_assets.go:57] converting resource: asset type serviceusage.googleapis.com/Service: asset name //serviceusage.googleapis.com/projects/prj-cloudbuild-/services/billingbudgets.googleapis.com: duplicate asset
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: W0224 01:10:40.899819     493 planned_assets.go:57] converting resource: asset type serviceusage.googleapis.com/Service: asset name //serviceusage.googleapis.com/projects/prj-cloudbuild-/services/compute.googleapis.com: duplicate asset
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: W0224 01:10:40.899852     493 planned_assets.go:57] converting resource: asset type serviceusage.googleapis.com/Service: asset name //serviceusage.googleapis.com/projects/prj-cloudbuild-/services/iamcredentials.googleapis.com: duplicate asset
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: W0224 01:10:40.900098     493 planned_assets.go:57] converting resource: asset type cloudbilling.googleapis.com/ProjectBillingInfo: asset name //cloudbilling.googleapis.com/projects/prj-cloudbuild-/billingInfo: duplicate asset

**Comment by jasonbisson** [comment] 2021-02-24 01:57
The only thing I can think of is the org terraform account is a billing admin and user roles

**Comment by melinath** [comment] 2021-02-24 16:50
Hi @jasonbisson - What exactly is the issue you're seeing? Is the validate run failing? The error in the title seems to be a combination of [glog over-logging](https://github.com/kubernetes/minikube/issues/4866) and a "duplicate asset" warning (which is non-blocking).

**Comment by jasonbisson** [comment] 2021-02-25 13:13
@melinath Thanks for the quick response. I had to bypass validator to complete the deployment, but I realize I didn't give the end of error log  which has a clear error message about the policies missing.

//serviceusage.googleapis.com/projects/prj-cloudbuild-b/services/pubsub.googleapis.com: duplicate asset
Step #1 - "tf plan validate all": Error: validating: FCV: initializing gcv validator: failed to read files in /workspace/policy-library/policies: error visiting path /workspace/policy-library/policies: lstat /workspace/policy-library/policies: no such file or directory
Step #1 - "tf plan validate all": Usage:
Step #1 - "tf plan validate all":   terraform-validator validate <tfplan> [flags]
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Flags:
Step #1 - "tf plan validate all":       --ancestry string      Override the ancestry location of the project when validating resources
Step #1 - "tf plan validate all":   -h, --help                 help for validate
Step #1 - "tf plan validate all":       --offline              Do not connect to GCP API
Step #1 - "tf plan validate all":       --output-json          Print violations as JSON
Step #1 - "tf plan validate all":       --policy-path string   Path to directory containing validation policies
Step #1 - "tf plan validate all":       --project string       Provider project override (override the default project configuration assigned to the google terraform provider when validating resources)
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Global Flags:
Step #1 - "tf plan validate all":       --verbose   Log output to stderr
Step #1 - "tf plan validate all":

**Comment by melinath** [comment] 2021-02-25 17:19
Ah, gotcha! Looking up a little in the logs, I also see the lines:

```
Step #1 - "tf plan validate all": Cloning into '/workspace/policy-library'...
[...]
Step #1 - "tf plan validate all": warning: You appear to have cloned an empty repository.
Step #1 - "tf plan validate all": Project [prj-cloudbuild-] repository [gcp-policies] was cloned to [/workspace/policy-library].
```

It seems like this might be an issue with cloning the repository rather than with terraform-validator.

**Comment by jasonbisson** [comment] 2021-02-26 13:16
@bharathkkb 

Hi Bharath It looks like source of the problem is gcp-policies is empty. Can you help me determine where the failure to populate the repo occurred? Assuming the bootstrap...

**Comment by bharathkkb** [comment] 2021-02-26 17:28
Hi @jasonbisson 
Could you check if [step 3](https://github.com/terraform-google-modules/terraform-example-foundation/tree/develop/1-org#setup-to-run-via-cloud-build) was completed and if the repo has the policies?

@melinath is this the expected behavior with an empty policy dir? Would it make sense to have a more descriptive error if no policies are found, happy to submit a PR.

**Comment by melinath** [comment] 2021-02-26 17:44
> @melinath is this the expected behavior with an empty policy dir? Would it make sense to have a more descriptive error if no policies are found, happy to submit a PR.

It looks like this error is coming [from config-validator core](https://github.com/forseti-security/config-validator/blob/1d64ba7f6d2483e39ab5aed8df5d8e87cccf1405/pkg/gcv/configs/file.go#L134) during the call to [NewValidator](https://github.com/forseti-security/config-validator/blob/1d64ba7f6d2483e39ab5aed8df5d8e87cccf1405/pkg/gcv/validator.go#L145)

I agree with config-validator that this is probably an error case. But yeah, this error message isn't super clear. If you'd like to submit a PR to catch the error case and give a better error message, that would be great!

**Comment by jasonbisson** [comment] 2021-02-26 18:54
@bharathkkb You nailed it. Missed that manual task. I'll update the repo and we can close it out on my side.

**Comment by melinath** [comment] 2021-02-26 21:17
Cool :-) I'll go ahead and close this issue.

**Closed by melinath** 2021-02-26 21:17 UTC
