### ISSUE TITLE
Offline mode does not work for `google_compute_instance`

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/terraform-validator#125] opened 2020-02-11 21:09 UTC
Terraform config to reproduce:
```
resource "google_compute_instance" "bad" {
  name         = "test-vm"
  project      = "test-project"
  machine_type = "n1-standard-1"
  zone         = "us-central1-a"
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  network_interface {
    network = "default"
    access_config {
      // Ephemeral IP
    }
  }
}
```
Terraform Validator version: Build version: 2020-01-23

Command:
```
terraform-validator-linux-amd64 validate \
  plan.json \
  --offline \
  --ancestry=organization/my-org/folder/my-folder \
  --project=test-project \
  --policy-path=./policy-library
```

Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x1786f7e]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraform-google-conversion/google.resolveImageImageExists(0xc000021400, 0xc00047a580, 0xc, 0xc00047a58d, 0x8, 0x17, 0xc00047a580, 0x15)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/image.go:47 +0x3e
github.com/GoogleCloudPlatform/terraform-google-conversion/google.resolveImage(0xc000021400, 0xc00046ac60, 0xc, 0xc00047a580, 0x15, 0x1bdb001, 0x24c9aa0, 0xc00012f600, 0x24f9328)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/image.go:143 +0x10a4
github.com/GoogleCloudPlatform/terraform-google-conversion/google.expandBootDisk(0x2959340, 0xc000466920, 0xc000021400, 0xc00046ac60, 0xc, 0x1, 0x24fdaeb, 0xc)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/compute_instance.go:270 +0x900
github.com/GoogleCloudPlatform/terraform-google-conversion/google.expandComputeInstance(0xc00046ac60, 0xc, 0x2959340, 0xc000466920, 0xc000021400, 0xc00046ac60, 0xc, 0x0)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/compute_instance.go:71 +0x1663
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetComputeInstanceApiObject(0x2959340, 0xc000466920, 0xc000021400, 0x2561f5d, 0x4f, 0xc0005a0060)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/compute_instance.go:46 +0xa2
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetComputeInstanceCaiObject(0x2959340, 0xc000466920, 0xc000021400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30, ...)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/compute_instance.go:24 +0xdc
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).AddResource(0xc0002958c0, 0x294ffa0, 0xc000097f40, 0xc0002958f0, 0xc000097f00)
	/Users/morgantep/code/google/validator/terraform-validator/converters/google/convert.go:144 +0x14c
github.com/GoogleCloudPlatform/terraform-validator/tfgcv.ReadPlannedAssets(0x7fff3e007bd0, 0x9, 0x7fff3e007c1e, 0xc, 0x7fff3e007bef, 0x24, 0xc000535c01, 0x0, 0x0, 0x0, ...)
	/Users/morgantep/code/google/validator/terraform-validator/tfgcv/planned_assets.go:93 +0x6bf
github.com/GoogleCloudPlatform/terraform-validator/cmd.glob..func6(0x3c620a0, 0xc00056ef00, 0x1, 0x5, 0x0, 0x0)
	/Users/morgantep/code/google/validator/terraform-validator/cmd/validate.go:54 +0xab
github.com/spf13/cobra.(*Command).execute(0x3c620a0, 0xc00056eeb0, 0x5, 0x5, 0x3c620a0, 0xc00056eeb0)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x3c61e20, 0x0, 0x0, 0x1d9ebf9)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/morgantep/code/google/validator/terraform-validator/vendor/github.com/spf13/cobra/command.go:864
github.com/GoogleCloudPlatform/terraform-validator/cmd.Execute()
	/Users/morgantep/code/google/validator/terraform-validator/cmd/root.go:77 +0x2e
main.main()
	/Users/morgantep/code/google/validator/terraform-validator/main.go:20 +0x20

```

The same command works for `google_project` and `google_storage_bucket`.

**Comment by morgante** [comment] 2020-02-11 21:11
@yukinying: This sounds like one of the errors you might have come across. Do you know the current state of evaluating instances in offline mode?

**Comment by yukinying** [comment] 2020-02-13 00:42
The issue was discussed in https://github.com/GoogleCloudPlatform/terraform-validator/issues/89.

On a security perspective, you may want to change the image path to something deterministic like "projects/debian-cloud/global/images/debian-9" because "debian-cloud/debian-9" could be resolved to differnet things depend on your project. That would avoid the panic.

**Comment by morgante** [comment] 2020-02-13 03:03
Closing as a duplicate of #89.

**Closed by morgante** 2020-02-13 03:03 UTC
