### ISSUE TITLE
Issues when scanning a plan that creates folders, projects within those folders

### ISSUE THREAD

**Issue by jdav-goog** [GoogleCloudPlatform/terraform-validator#145] opened 2020-06-23 15:18 UTC
We are trying to deploy new folders, folder IAM, org policies and projects within those folders. I'm not sure if this is currently supported by the validator. 

First we get an error that project field is not set, although google_folder_iam_binding doesn't require a project.
![image](https://user-images.githubusercontent.com/61511931/85412793-98cec700-b52f-11ea-88c2-f80442a2e2fc.png)

We run the same thing with a project field arbitrarily set, but we get an "Error 403: Request had insufficient authentication scopes."
![image](https://user-images.githubusercontent.com/61511931/85416893-9c188180-b534-11ea-99ce-e6b9b4f1ea00.png)

Is the workaround here to use --offline and --ancestry?

**Comment by morgante** [comment] 2020-06-23 16:18
Yes, we currently can't parse the ancestry of folders and projects until they've been created—using `--offline` and `--ancestry` is the suggested workaround.

**Comment by melinath** [comment] 2021-03-24 18:58
Closing as a duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/206 - if you believe this is in error, please reopen. Otherwise, please upvote the other issue. Thanks!

**Closed by melinath** 2021-03-24 18:58 UTC
Labels: bug
