### ISSUE TITLE
update fetching asset: empty identity field

### ISSUE THREAD

**Issue by sailaxman** [GoogleCloudPlatform/terraform-validator#254] opened 2021-07-16 03:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Terraform Validator version

terraform-validator: v0.3.0 and v0.2.0

### Affected Resource(s)

all

### Terraform Plan JSON

[plan.json.zip](https://github.com/GoogleCloudPlatform/terraform-validator/files/6827635/plan.json.zip)

### Debug Output

https://gist.github.com/sailaxman/e96cec2925f1a3d83251d7596245f72a

### Expected Behavior

validate the plan

### Actual Behavior

failing to validate the plan

### Steps to Reproduce

terraform-validator validate plan.json --project ${TF_GCP_PROJECT} --policy-path=../../../gcp-policy-library/policy-library/ --verbose

* b/195129237

**Comment by melinath** [comment] 2021-07-16 15:31
This is a duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/139 - terraform-validator can't handle random / known after apply project ids.

**Comment by sailaxman** [comment] 2021-07-16 23:49
hi @melinath,

It is not related to that above issue, I have verified the same state json file with  terraform-validator 0.1.0 and working as expected.

**Comment by palani-ram-google-partner** [comment] 2021-07-29 20:22
We have encountered the same issue. Here is the log output.

$ ./terraform-validator validate --verbose --project prj-bluechip-0c07 secure.json --policy-path ~/policy-library                                                                                          [18:02:45]
2021/07/27 18:03:36 [INFO] Authenticating using DefaultClient...
2021/07/27 18:03:36 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/07/27 18:03:36 [INFO] Authenticating using DefaultClient...
2021/07/27 18:03:36 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/07/27 18:03:36 [DEBUG] Waiting for state to become: [success]
2021/07/27 18:03:36 [INFO] Terraform is using this identity: test@somedomain.com
ERROR: logging before flag.Parse: I0727 18:03:36.908539   57177 convert.go:204] unsupported resource: google_compute_global_address
ERROR: logging before flag.Parse: I0727 18:03:36.908575   57177 convert.go:204] unsupported resource: google_compute_route
ERROR: logging before flag.Parse: I0727 18:03:36.908586   57177 convert.go:204] unsupported resource: google_project_iam_custom_role
ERROR: logging before flag.Parse: I0727 18:03:36.908595   57177 convert.go:204] unsupported resource: google_service_networking_connection
ERROR: logging before flag.Parse: I0727 18:03:36.908602   57177 convert.go:204] unsupported resource: google_compute_router
ERROR: logging before flag.Parse: I0727 18:03:36.908609   57177 convert.go:204] unsupported resource: google_compute_router_nat
ERROR: logging before flag.Parse: I0727 18:03:36.908617   57177 convert.go:204] unsupported resource: google_service_account
ERROR: logging before flag.Parse: I0727 18:03:36.908624   57177 convert.go:198] unknown resource: random_shuffle
ERROR: logging before flag.Parse: I0727 18:03:36.908726   57177 convert.go:198] unknown resource: random_string
**Error: converting tfplan to CAI assets: adding resource changes to converter: adding resource create or update fetching asset: empty identity field**

**Comment by c2thorn** [comment] 2021-08-02 14:54
Hi @sailaxman, @palani-ram-google-partner 

I've looked into this issue and confirmed that is resolved after https://github.com/GoogleCloudPlatform/terraform-validator/pull/218 was merged. If you try `v0.3.1` or later of Validator, you should see the error turn into a warning and pass.

Please try this out and let me know!

**Closed** 2021-08-02 14:58 UTC
Labels: bug

**Comment by sailaxman** [comment] 2021-08-02 23:04
hi @c2thorn ,

Verified with v0.4.0 and not seeing this issue anymore, thank you
